export const ADD_TODO = "ADD_TODO";
export const TOOGLE_TODO = "TOOGLE_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const SET_FILTER_TYPE = "SET_FILTER_TYPE";

export const FILTER_TYPE = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  SHOW_UNCOMPLETED: "SHOW_UNCOMPLETED",
};
